# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TotoReactTraining' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TotoReactTraining
  pod 'GoogleSignIn'

  target 'TotoReactTrainingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TotoReactTraining-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TotoReactTraining-tvOS

  target 'TotoReactTraining-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
